# Generated by Django 5.1 on 2024-12-20 10:58

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('server_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('donate_balance', models.IntegerField(default=0)),
                ('job_lvl', models.IntegerField(default=1)),
                ('nickname', models.JSONField(default=users.models.default_nickname)),
                ('money', models.JSONField(default=users.models.default_money)),
                ('job', models.JSONField(default=users.models.default_job)),
                ('house', models.JSONField(default=users.models.default_house)),
                ('car', models.JSONField(default=users.models.default_car)),
                ('yacht', models.JSONField(default=users.models.default_yacht)),
                ('couple', models.JSONField(default=users.models.default_couple)),
                ('registration', models.DateField(auto_now=True)),
                ('language', models.CharField(default='ru', max_length=10)),
                ('username_tg', models.CharField(default=None, max_length=100)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
