# Generated by Django 4.1.13 on 2024-06-24 20:49

from django.db import migrations, models
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('server_id', models.IntegerField(default=1)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('donate_balance', models.IntegerField(default=0)),
                ('job_lvl', models.IntegerField(default=1)),
                ('nickname', models.JSONField(default=users.models.default_nickname)),
                ('money', models.JSONField(default=users.models.default_money)),
                ('job', models.JSONField(default=users.models.default_job)),
                ('house', models.JSONField(default=users.models.default_house)),
                ('car', models.JSONField(default=users.models.default_car)),
                ('yacht', models.JSONField(default=users.models.default_yacht)),
                ('couple', models.JSONField(default=users.models.default_couple)),
                ('registration', models.DateField(auto_now=True)),
                ('language', models.CharField(default='ru', max_length=10)),
                ('username_tg', models.CharField(default=None, max_length=100)),
                ('groups', models.ManyToManyField(blank=True, related_name='%(class)s_groups', related_query_name='%(class)s_group', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='%(class)s_user_permissions', related_query_name='%(class)s_user_permission', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'lerkalalka',
            },
        ),
    ]
