# Generated by Django 5.1 on 2025-01-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='server_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
