# Generated by Django 5.1 on 2025-01-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_items_alter_car_table_alter_districts_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='attributes',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
