# Generated by Django 5.1 on 2025-01-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('level', models.IntegerField(choices=[(1, 'Дворник'), (2, 'Риелтор'), (3, 'Банкир'), (4, 'Автодилер'), (5, 'Коллекционер'), (6, 'Трейдер'), (7, 'Крупье')])),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('required_exp', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
    ]
