# Generated by Django 5.1 on 2025-01-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='sphere',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
