# Generated by Django 5.1 on 2025-01-10 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prize_type', models.CharField(choices=[('item', 'Item'), ('cash', 'Cash'), ('freespin', 'FreeSpin')], default='item', max_length=50)),
                ('prize_value', models.IntegerField()),
                ('stake_value', models.DecimalField(decimal_places=7, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FreeSpinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prize_value', models.IntegerField()),
                ('stake_value', models.IntegerField()),
                ('currency', models.CharField(default='USD', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CasinoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_win', models.IntegerField(default=30)),
                ('freespins_available', models.IntegerField(default=0)),
                ('current_stake', models.IntegerField()),
                ('bonuses', models.ManyToManyField(related_name='casino_entries', to='casino.bonus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casino', to=settings.AUTH_USER_MODEL)),
                ('free_spin_types', models.ManyToManyField(related_name='casino_entries', to='casino.freespintype')),
            ],
            options={
                'db_table': 'casino',
            },
        ),
    ]
