# Generated by Django 5.1 on 2025-01-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casinomodel',
            name='bonuses',
            field=models.ManyToManyField(related_name='casino_bonuses', to='casino.bonus'),
        ),
        migrations.AlterField(
            model_name='casinomodel',
            name='free_spin_types',
            field=models.ManyToManyField(related_name='casino_freespins', to='casino.freespintype'),
        ),
    ]
