# Generated by Django 5.1 on 2025-01-10 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0002_alter_casinomodel_bonuses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casinomodel',
            name='bonuses',
        ),
    ]
