# Generated by Django 5.1 on 2025-01-10 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0003_remove_casinomodel_bonuses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bonus',
        ),
    ]
