# Generated by Django 5.1 on 2025-01-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0005_casinomodel_max_win_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='casinomodel',
            name='max_cash_win_type',
            field=models.CharField(default='cash', max_length=100, null=True),
        ),
    ]
