# Generated by Django 5.1 on 2025-01-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0006_casinomodel_max_cash_win_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='casinomodel',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
