# Generated by Django 5.1 on 2025-01-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0007_casinomodel_is_authenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casinomodel',
            name='max_cash_win_type',
            field=models.CharField(default='USD', max_length=100, null=True),
        ),
    ]
