"""
Django settings for richMachine project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

from django.template.context_processors import static

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y8cr906v^k!mmn^z6mqnv2+$1p#9*u!$s0fh=c65z3-b+6o(w('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'daphne',
    'homePage',

    'inventory',
    'casino',
    'channels',
    'users',
    'magazine',
    'jobs',
    'django_filters',
    'corsheaders',
    'API',
    'rest_framework',
    'rest_framework.authtoken',
    # 'django_ratelimit',
    'django.contrib.humanize',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

ASGI_APPLICATION = 'richMachine.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379)],
        },
    },
}

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',  # URL Redis-сервера
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'IGNORE_EXCEPTIONS': True,  # Игнорировать ошибки подключения (рекомендуется для production)
        }
    }
}

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    )
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.ContentSecurityPolicyMiddleware',
    'users.middleware.RequestSourceMiddleware',
    'users.middleware.AuthenticationUserMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'users.telegram_backend.TelegramBackend',
    'django.contrib.auth.backends.ModelBackend',
]
TELEGRAM_BOT_TOKEN = '6534598365:AAGxpSaIXsDU2Gr44k-wEfd_8zec6SAuxTg'

ROOT_URLCONF = 'richMachine.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'richMachine.context_processors.messages_json',
            ],
        },
    },
]

WSGI_APPLICATION = 'richMachine.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "richmachine",
        "USER": "postgres",
        "PASSWORD": "Evrirus",
        "HOST": "127.0.0.1",
        "PORT": "5432",
    }
}


SESSION_ENGINE = 'django.contrib.sessions.backends.file'  # Use database-backed sessions
SESSION_COOKIE_NAME = 'sessionid'


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'homePage' / 'static',
    BASE_DIR / 'magazine' / 'static/',
    BASE_DIR / 'users' /'static/',
    # BASE_DIR / 'other_functions' / 'static/',
    BASE_DIR / 'casino' / 'static/',
    BASE_DIR / 'inventory' / 'static/',
    BASE_DIR / 'jobs' / 'static/',
    
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "users.CustomUser"

LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"
CSRF_TRUSTED_ORIGINS = ['https://f6ec-5-228-83-61.ngrok-free.app']
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'
CORS_ORIGIN_WHITELIST = (
'http://localhost:8000',  # for localhost (REACT Default)
'https://f6ec-5-228-83-61.ngrok-free.app', # for network
)
# В файле settings.py вашего Django-приложения
CSP_FRAME_ANCESTORS = ("'self'", "https://*.t.me")
# X_FRAME_OPTIONS = 'DENY'
# CSRF_COOKIE_SAMESITE = None
